apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: java-app
  name: nexus-app
  labels:
    app: nexus-app
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-app
      env: test
  template:
    metadata:
      labels:
        app: nexus-app
        env: test
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:3.83.1-alpine
        ports:
        - containerPort: 8081
          name: nexus-port
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 180
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 180
          periodSeconds: 20
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-data
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nexus-ready
                operator: In
                values: 
                - "true"
      tolerations:
      - key: nexus-ready
        operator: Equal
        value: "true"
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  namespace: java-app
  name: nexus-svc
spec:
  selector:
    app: nexus-app
    env: test
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
    protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /nexus-data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nexus-ready
          operator: In
          values:
          - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: java-app
  name: nexus-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
  volumeName: nexus-pv